micronaut:
  application:
    name: lia_micronaut
    max: 50

datasources:
  default:
    url: jdbc:mysql://localhost:3306/liaproject_micronaut
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    schema-generate: NONE
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update
