micronaut:
  application:
    name: lia_micronaut
datasources:
  default:
    url: jdbc:mysql://localhost:3306/liaproject_micronaut
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    schema-generate: NONE
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
    packages-to-scan: "com.example.entities"